server:
  port: 8503

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka

spring:
  applicaion:
    name: notification-service
  rabbitmq:
    username: username
    password: password
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"